### ISSUE TITLE
Spotify playback error

### ISSUE THREAD

**Issue by jaedb** [jojo141185/mopidy-docker#2]
I am able to add a Spotify track to the queue, however when attempting to play this Spotify track I receive the following (in the Mopidy log):
```
mopidy_1          | ERROR    2022-12-10 00:23:03,797 [8:MainThread] mopidy.audio.gst
mopidy_1          |   GStreamer error: Could not get/set settings from/on resource.
```

I know this is early days of the revamped Mopidy-Spotify extension so am expecting to need to do some extra tinkering to get this working. Where should I start looking?

I have tried both the `master` and `develop` branch Dockerfiles, and playing local or YTMusic audio works fine.

**Comment by jojo141185** [comment]
Hi jaedb,
can you please check if the problem is related to the credential cache of gst-plugins-spotify. The error seems to be very similar to yours. I have added the point in the [wiki](https://github.com/jojo141185/mopidy-docker/wiki/Test-Spotify-playback). 
Delete the credentials.json file in the container as described and try again. 
Hope this solves the problem :crossed_fingers:

**Comment by jaedb** [comment]
Initially it _was_ related to credentials, but after enabling extra logging in `mopidy.conf` with:
```
[logging]
verbosity = 4
```
it seemed the issue was actually with file-system access to the `/tmp` folder when. As a rude test of this theory, I `chmod 755 -R /tmp` and all worked. Then running a full `--no-cache` rebuild the issue was gone 🤷

I'll close this issue now 😄
