### ISSUE TITLE
ARM64 image

### ISSUE THREAD

**Issue by RogierTimmer** [jojo141185/mopidy-docker#5]
Hi! Thanks for creating a Docker image of `mopidy:edge`, it looks amazing! Unfortunately I'd like to run this on a raspberry pi (`arm64`) and that isn't supported right now.

I saw that there was some support in the Dockerfile ([L39](https://github.com/jojo141185/mopidy-docker/blob/main/Dockerfile#L39)) for `arm64`, but I am not very comfortable with Docker so I'm not sure how to do this myself. Do you have any pointers, or are you able to create a docker image for `arm64`? Thanks!

**Comment by jojo141185** [comment]
I have created an arm64 image for you. But as I don't have any arm64 compatible hardware, I need your help to test it. 
You can pull it from dockerhub: `docker pull jojo141185/mopidy:arm64`
If all works and it does not lead to compatibility problems in the build process, I will be able to provide arm64 images as well in the future.

**Comment by hagemier** [comment]
Thank you so much for this image.  I have the arm64 image running fine on a rock64 board.  I do have one question.  I can start the image fine using a docker run command but when I tried to use a docker compose file I get this error.

mopidy  | [dumb-init] /entrypoint.sh: Permission denied
mopidy exited with code 0

here is my compose file

version: '3.3'
services:
    mopidy:
        container_name: mopidy
        restart: unless-stopped
        volumes:
            - './config/:/config'
            - '/home/jacob/Music/:/var/lib/mopidy/media:ro'
            - './local:/var/lib/mopidy/.local'
            - './fifo:/sound'
        ports:
            - '6600:6600'
            - '6680:6680'
        image: 'jojo141185/mopidy:arm64'

I get the same error on an amd64 machine.  Not a huge issue,  just curious what I may be doing wrong.

I guess one more thing to mention is  that your documentation says to map a volume to /var/lib/mopidy/local but the image does not seem to use that directory.  Library database and images are saved in child directories of .local so that is why I am using that in the compose file.  

Thank you again

**Comment by jojo141185** [comment]
I think the error is related to the missing permissions of your user. 
Try adding the directive "user: root" to your docker-compose.yml file.

**Comment by RogierTimmer** [comment]
Thanks for the inclusion of ARM64, it works now. It is indeed necessary to include user:root.
